/**
 * Project export: emitter output + per-target build scaffolding (README with
 * exact run steps, .gitignore where useful) packaged for a one-command build.
 *
 * Flutter note: `flutter create .` regenerates the android/ ios/ platform
 * folders inside an exported project, so shipping pubspec + lib is enough for
 * a fully buildable app.
 */
import type { App } from './ir';
import { emit } from './emitters/index';
import type { EmittedFile, TargetLang } from './emitters/types';

function readme(lines: string[]): string { return lines.join('\n') + '\n'; }

const EXTRAS: Record<TargetLang, (app: App) => EmittedFile[]> = {
  flutter: (app) => [
    {
      path: 'README.md',
      language: 'text',
      contents: readme([
        `# ${app.name} (Flutter)`,
        '',
        'Generated by Aelix Canvas. Builds for **Android and iOS** from this one codebase.',
        '',
        '## Run on your phone / emulator',
        '1. Install the Flutter SDK: https://docs.flutter.dev/get-started/install',
        '2. In this folder, generate the platform scaffolding (first time only):',
        '   ```',
        '   flutter create .',
        '   ```',
        '3. Plug in a device (USB debugging on) or start an emulator, then:',
        '   ```',
        '   flutter run',
        '   ```',
        '',
        '## Release APK',
        '```',
        'flutter build apk --release',
        '```',
        'Output: build/app/outputs/flutter-apk/app-release.apk',
      ]),
    },
    { path: '.gitignore', language: 'text', contents: 'build/\n.dart_tool/\n.idea/\n*.iml\n' },
  ],
  html: (app) => [
    {
      path: 'README.md',
      language: 'text',
      contents: readme([
        `# ${app.name} (Web)`,
        '',
        'Generated by Aelix Canvas. Open `index.html` in any browser — no build step.',
        'Host the folder anywhere (GitHub Pages, Netlify) to use it on a phone as a web app.',
      ]),
    },
  ],
  swiftui: (app) => [
    {
      path: 'README.md',
      language: 'text',
      contents: readme([
        `# ${app.name} (SwiftUI)`,
        '',
        'Generated by Aelix Canvas. Requires **Xcode on macOS**.',
        '',
        '1. Xcode → File → New → Project → iOS App (SwiftUI, name it accordingly).',
        '2. Replace the generated App/ContentView files with `Sources/App.swift`.',
        '3. Run on a simulator or device (⌘R).',
      ]),
    },
  ],
  compose: (app) => [
    {
      path: 'README.md',
      language: 'text',
      contents: readme([
        `# ${app.name} (Jetpack Compose)`,
        '',
        'Generated by Aelix Canvas. Native **Android**.',
        '',
        '1. Android Studio → New Project → Empty Activity (Compose), package `com.aelix.generated`.',
        '2. Replace `MainActivity.kt` with the one in `app/src/main/java/com/aelix/generated/`.',
        '3. Add the dependencies from `app/build.gradle.deps.kts` to your app-level build.gradle.kts.',
        '4. Run on an emulator or device.',
      ]),
    },
  ],
  tkinter: (app) => [
    {
      path: 'README.md',
      language: 'text',
      contents: readme([
        `# ${app.name} (Python / Tkinter)`,
        '',
        'Generated by Aelix Canvas. Needs only Python 3 (Tkinter is in the stdlib).',
        '',
        '```',
        'python main.py',
        '```',
      ]),
    },
  ],
  wpf: (app) => [
    {
      path: 'README.md',
      language: 'text',
      contents: readme([
        `# ${app.name} (C# WPF)`,
        '',
        'Generated by Aelix Canvas. Complete .NET 8 WPF project (Windows).',
        '',
        '```',
        'dotnet run',
        '```',
      ]),
    },
  ],
  swing: (app) => [
    {
      path: 'README.md',
      language: 'text',
      contents: readme([
        `# ${app.name} (Java / Swing)`,
        '',
        'Generated by Aelix Canvas. Needs a JDK (17+ recommended).',
        '',
        '```',
        'javac Main.java',
        'java Main',
        '```',
      ]),
    },
  ],
};

/** Emitter files + build scaffolding for a downloadable, buildable project. */
export function exportProject(app: App, target: TargetLang): EmittedFile[] {
  return [...emit(app, target), ...EXTRAS[target](app)];
}
